spring:
  datasource:
    url: jdbc:h2:mem:notesdb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

server:
  port: 8080

  servlet:
    context-path: /api/v1


jwt:
  secret: 8E2iB7fZgqZpO7kH6WZK7ZsE3iH4zF3tQ5gO2hN3jR6lX8vZ9pF6yC2hX5jG7mN4oT5xW8qV7mQ2rF4zX6nH9aU8wS7lB3jR
  expiration: 3600000  # 1 hour in milliseconds