### POST request  to create new note
POST http://localhost:8080/api/v1/notes/create
Content-Type: application/json
Accept: application/json
Authorization: "Bearer" +"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbm9ueW1vdXNVc2VyIiwiaWF0IjoxNzU2MjMwOTc4LCJleHAiOjE3NTYyMzQ1Nzh9.7CyspC4UpUPzW9kNMi5DxNYmxTOrMrxeJ4Jqs7WlL1PRVbRaCcJyQ-jbBgLjp6B6RhlAbq6hm9jZlCaglyNB-g"

{
  "title": "First Note",
  "content": "This is my first note"
}